/* Auto-generated weak stubs for missing symbols */

#include <platform.h>

/* Forward declarations for types used in stub signatures */
struct Fighter;
typedef struct Fighter Fighter;
typedef struct HSD_GObj Fighter_GObj;

/* ef module stubs */
__attribute__((weak)) int efAsync_LoadAsync(void*, void*, void*, void*, void*) { return 0; }
__attribute__((weak)) int efAsync_LoadSync(void*, void*, void*, void*, void*) { return 0; }
__attribute__((weak)) void efAsync_QueueClear(void) { }
__attribute__((weak)) void efAsync_QueueFlush(void) { }
__attribute__((weak)) void* efAsync_Spawn(void*, void*, void*, void*, void*) { return NULL; }
__attribute__((weak)) void efLib_DestroyAll(void) { }
__attribute__((weak)) void efLib_PauseAll(void) { }
__attribute__((weak)) void efLib_ResumeAll(void) { }
__attribute__((weak)) void efLib_SetParamAlpha(void*, float) { }

/* ft module stubs - character init functions */
__attribute__((weak)) void ftBo_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftBo_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftBo_Init_DataName(void) { }
__attribute__((weak)) void ftBo_Init_DatFilename(void) { }
__attribute__((weak)) void ftBo_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftBo_Init_OnDeath(void) { }
__attribute__((weak)) void ftBo_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftBo_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftBo_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftBo_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftBo_Init_OnLoad(void) { }

__attribute__((weak)) void ftCa_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftCa_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftCa_Init_DataName(void) { }
__attribute__((weak)) void ftCa_Init_DatFilename(void) { }
__attribute__((weak)) void ftCa_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftCa_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftCa_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftCa_Init_OnDeath(void) { }
__attribute__((weak)) void ftCa_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftCa_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftCa_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftCa_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftCa_Init_OnLoad(void) { }
__attribute__((weak)) void ftCa_SpecialAirHi_Enter(Fighter_GObj*) { }
__attribute__((weak)) void ftCa_SpecialAirLw_Enter(Fighter_GObj*) { }
__attribute__((weak)) void ftCa_SpecialAirN_Enter(Fighter_GObj*) { }
__attribute__((weak)) void ftCa_SpecialAirS_Enter(Fighter_GObj*) { }
__attribute__((weak)) void ftCa_SpecialHi_Enter(Fighter_GObj*) { }
__attribute__((weak)) void ftCa_SpecialLw_Enter(Fighter_GObj*) { }
__attribute__((weak)) void ftCa_SpecialN_Enter(Fighter_GObj*) { }
__attribute__((weak)) void ftCa_SpecialS_Enter(Fighter_GObj*) { }

/* ft character stubs */
__attribute__((weak)) void ftCh_GrabUnk1_8015ADD0(void) { }
__attribute__((weak)) void ftCh_GrabUnk1_8015BC88(void) { }
__attribute__((weak)) void ftCh_Init_80155FCC(void) { }
__attribute__((weak)) void ftCh_Init_80156014(void) { }
__attribute__((weak)) void ftCh_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftCh_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftCh_Init_DataName(void) { }
__attribute__((weak)) void ftCh_Init_DatFilename(void) { }
__attribute__((weak)) void ftCh_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftCh_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftCh_Init_OnDeath(void) { }
__attribute__((weak)) void ftCh_Init_OnLoad(void) { }

__attribute__((weak)) void ftCl_Init_8014919C(void) { }
__attribute__((weak)) void ftCl_Init_80149318(void) { }
__attribute__((weak)) void ftCl_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftCl_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftCl_Init_DataName(void) { }
__attribute__((weak)) void ftCl_Init_DatFilename(void) { }
__attribute__((weak)) void ftCl_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftCl_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftCl_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftCl_Init_OnDeath(void) { }
__attribute__((weak)) void ftCl_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftCl_Init_OnItemDropExt(void) { }
__attribute__((weak)) void ftCl_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftCl_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftCl_Init_OnItemPickupExt(void) { }
__attribute__((weak)) void ftCl_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftCl_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftCl_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftCl_Init_OnLoad(void) { }

/* ft common capture stubs */
__attribute__((weak)) void ftCo_CaptureCrazyHand_Anim(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureCrazyHand_Coll(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureCrazyHand_IASA(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureCrazyHand_Phys(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureDamageCrazyHand_Anim(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureDamageCrazyHand_Coll(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureDamageCrazyHand_IASA(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureDamageCrazyHand_Phys(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureKirbyYoshi_Anim(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureKirbyYoshi_Coll(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureKirbyYoshi_IASA(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureKirbyYoshi_Phys(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureWaitCrazyHand_Anim(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureWaitCrazyHand_Coll(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureWaitCrazyHand_IASA(Fighter_GObj*) { }
__attribute__((weak)) void ftCo_CaptureWaitCrazyHand_Phys(Fighter_GObj*) { }

/* gm module stubs */
__attribute__((weak)) int gmDecisionGetType(void) { return 0; }
__attribute__((weak)) void gm_80167470(void) { }
__attribute__((weak)) void gm_801693BC(void) { }
__attribute__((weak)) void gm_8016B014(void) { }
__attribute__((weak)) void gm_8016B094(void) { }
__attribute__((weak)) void gm_8016B0B4(void) { }
__attribute__((weak)) void gm_8016B0D4(void) { }
__attribute__((weak)) void gm_8016B0E8(void) { }
__attribute__((weak)) void gm_8016B0FC(void) { }
__attribute__((weak)) void gm_8016B110(void) { }
__attribute__((weak)) void gm_8016B14C(void) { }
__attribute__((weak)) void gm_8016B1C4(void) { }
__attribute__((weak)) void gm_8016B1EC(void) { }
__attribute__((weak)) void gm_8016B204(void) { }
__attribute__((weak)) void gm_8016C5C0(void) { }

/* mp module stubs */
__attribute__((weak)) void mpCheckAll(void) { }
__attribute__((weak)) void mpCheckCeiling(void) { }
__attribute__((weak)) void mpIsland_8005AC14(void) { }
__attribute__((weak)) void mpIsland_8005ACE8(void) { }

/* it module stubs */
__attribute__((weak)) void it_8026B924(void) { }
__attribute__((weak)) void it_8026B960(void) { }
__attribute__((weak)) void it_8026C1B4(void) { }

/* cm module stubs */
__attribute__((weak)) void Camera_8002E818(void) { }
__attribute__((weak)) void Camera_8002EA64(void) { }
__attribute__((weak)) void Camera_8002F0E4(void) { }
__attribute__((weak)) void Camera_80030CD8(void) { }
__attribute__((weak)) void Camera_80030CFC(void) { }
__attribute__((weak)) void Camera_80030E10(void) { }
__attribute__((weak)) void Camera_80031060(void) { }
__attribute__((weak)) void Camera_800310B8(void) { }
__attribute__((weak)) void Camera_80031144(void) { }
__attribute__((weak)) void Camera_80031154(void) { }

/* if module stubs */
__attribute__((weak)) void ifStatus_802F69C0(void) { }
__attribute__((weak)) void ifStatus_802F6AF8(void) { }
__attribute__((weak)) void ifStatus_802F6C04(void) { }
__attribute__((weak)) void ifStatus_802F6D10(void) { }
__attribute__((weak)) void ifStatus_802F6E1C(void) { }

/* db module stubs */
__attribute__((weak)) void db_804D4AF8(void) { }

/* HSD baselib stubs */
__attribute__((weak)) void HSD_PadRumbleRemoveId(void) { }

/* ft motion stubs */
__attribute__((weak)) void ftMh_MS_343_80151484(void) { }

/* ft kirby stubs */
__attribute__((weak)) void ftKb_SpecialN_800EED50(void) { }
/* Auto-generated weak stubs for missing symbols (batch 2) */

#include <platform.h>

__attribute__((weak)) void Item_8026AB54(void) { }
__attribute__((weak)) void Item_8026ABD8(void) { }
__attribute__((weak)) void Item_8026AC74(void) { }
__attribute__((weak)) void Item_8026AD20(void) { }
__attribute__((weak)) void Item_IsGrabbable(void) { }
__attribute__((weak)) void ftCo_KirbyYoshiEgg_Anim(void) { }
__attribute__((weak)) void ftCo_KirbyYoshiEgg_Coll(void) { }
__attribute__((weak)) void ftCo_KirbyYoshiEgg_IASA(void) { }
__attribute__((weak)) void ftCo_KirbyYoshiEgg_Phys(void) { }
__attribute__((weak)) void ftCo_ThrownCrazyHand_Anim(void) { }
__attribute__((weak)) void ftCo_ThrownCrazyHand_Coll(void) { }
__attribute__((weak)) void ftCo_ThrownCrazyHand_IASA(void) { }
__attribute__((weak)) void ftCo_ThrownCrazyHand_Phys(void) { }
__attribute__((weak)) void ftDk_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftDk_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftDk_Init_DatFilename(void) { }
__attribute__((weak)) void ftDk_Init_DataName(void) { }
__attribute__((weak)) void ftDk_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftDk_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftDk_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftDk_Init_OnDeath(void) { }
__attribute__((weak)) void ftDk_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftDk_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftDk_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftDk_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftDk_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftDk_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftDk_Init_OnLoad(void) { }
__attribute__((weak)) void ftDk_Init_UnkMotionStates4(void) { }
__attribute__((weak)) void ftDk_MS_341_800DF980(void) { }
__attribute__((weak)) void ftDk_MS_349_800E06D8(void) { }
__attribute__((weak)) void ftDk_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftDk_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftDk_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftDk_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftDk_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftDk_SpecialN_Enter(void) { }
__attribute__((weak)) void ftDk_SpecialS_Enter(void) { }
__attribute__((weak)) void ftDr_Init_80149910(void) { }
__attribute__((weak)) void ftDr_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftDr_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftDr_Init_DatFilename(void) { }
__attribute__((weak)) void ftDr_Init_DataName(void) { }
__attribute__((weak)) void ftDr_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftDr_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftDr_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftDr_Init_OnDeath(void) { }
__attribute__((weak)) void ftDr_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftDr_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftDr_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftDr_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftDr_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftDr_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftDr_Init_OnLoad(void) { }
__attribute__((weak)) void ftFc_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftFc_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftFc_Init_DatFilename(void) { }
__attribute__((weak)) void ftFc_Init_DataName(void) { }
__attribute__((weak)) void ftFc_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftFc_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftFc_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftFc_Init_OnDeath(void) { }
__attribute__((weak)) void ftFc_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftFc_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftFc_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftFc_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftFc_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftFc_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftFc_Init_OnLoad(void) { }
__attribute__((weak)) void ftFe_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftFe_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftFe_Init_DatFilename(void) { }
__attribute__((weak)) void ftFe_Init_DataName(void) { }
__attribute__((weak)) void ftFe_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftFe_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftFe_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftFe_Init_OnDeath(void) { }
__attribute__((weak)) void ftFe_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftFe_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftFe_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftFe_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftFe_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftFe_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftFe_Init_OnLoad(void) { }
__attribute__((weak)) int ftFx_AppealS_CheckIfUsed(void) { return 0; }
__attribute__((weak)) int ftFx_AppealS_CheckInput(void) { return 0; }
__attribute__((weak)) void ftFx_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftFx_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftFx_Init_DatFilename(void) { }
__attribute__((weak)) void ftFx_Init_DataName(void) { }
__attribute__((weak)) void ftFx_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftFx_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftFx_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftFx_Init_OnDeath(void) { }
__attribute__((weak)) void ftFx_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftFx_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftFx_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftFx_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftFx_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftFx_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftFx_Init_OnLoad(void) { }
__attribute__((weak)) void ftFx_SpecialAirHiStart_Enter(void) { }
__attribute__((weak)) void ftFx_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftFx_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftFx_SpecialAirSStart_Enter(void) { }
__attribute__((weak)) void ftFx_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftFx_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftFx_SpecialN_Enter(void) { }
__attribute__((weak)) void ftFx_SpecialSStart_Enter(void) { }
__attribute__((weak)) void ftFx_Throw_Anim(void) { }
__attribute__((weak)) void ftGk_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftGk_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftGk_Init_DatFilename(void) { }
__attribute__((weak)) void ftGk_Init_DataName(void) { }
__attribute__((weak)) void ftGk_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftGk_Init_GetMotionFileString(void) { }
__attribute__((weak)) void ftGk_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftGk_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftGk_Init_OnDeath(void) { }
__attribute__((weak)) void ftGk_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftGk_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftGk_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftGk_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftGk_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftGk_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftGk_Init_OnLoad(void) { }
__attribute__((weak)) void ftGk_Init_UnkDemoCallbacks0(void) { }
__attribute__((weak)) void ftGk_Init_UnkMotionStates0(void) { }
__attribute__((weak)) void ftGk_Init_UnkMotionStates3(void) { }
__attribute__((weak)) void ftGl_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftGl_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftGl_Init_DatFilename(void) { }
__attribute__((weak)) void ftGl_Init_DataName(void) { }
__attribute__((weak)) void ftGl_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftGl_Init_OnDeath(void) { }
__attribute__((weak)) void ftGl_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftGl_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftGl_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftGl_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftGl_Init_OnLoad(void) { }
__attribute__((weak)) void ftGn_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftGn_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftGn_Init_DatFilename(void) { }
__attribute__((weak)) void ftGn_Init_DataName(void) { }
__attribute__((weak)) void ftGn_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftGn_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftGn_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftGn_Init_OnDeath(void) { }
__attribute__((weak)) void ftGn_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftGn_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftGn_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftGn_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftGn_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftGn_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftGn_Init_OnLoad(void) { }
__attribute__((weak)) void ftGw_Attack100Start_Enter(void) { }
__attribute__((weak)) void ftGw_Attack11_Enter(void) { }
__attribute__((weak)) void ftGw_AttackAirN_DecideAction(void) { }
__attribute__((weak)) void ftGw_AttackLw3_Enter(void) { }
__attribute__((weak)) void ftGw_AttackS4_Enter(void) { }
__attribute__((weak)) void ftGw_Init_8014A7F4(void) { }
__attribute__((weak)) void ftGw_Init_8014A814(void) { }
__attribute__((weak)) void ftGw_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftGw_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftGw_Init_DatFilename(void) { }
__attribute__((weak)) void ftGw_Init_DataName(void) { }
__attribute__((weak)) void ftGw_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftGw_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftGw_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftGw_Init_OnAbsorb(void) { }
__attribute__((weak)) void ftGw_Init_OnDeath(void) { }
__attribute__((weak)) void ftGw_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftGw_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftGw_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftGw_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftGw_Init_OnLoad(void) { }
__attribute__((weak)) void ftGw_Init_UnkMotionStates4(void) { }
__attribute__((weak)) void ftGw_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftGw_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftGw_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftGw_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftGw_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftGw_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftGw_SpecialN_Enter(void) { }
__attribute__((weak)) void ftGw_SpecialS_Enter(void) { }
__attribute__((weak)) void ftKb_Init_800EE528(void) { }
__attribute__((weak)) void ftKb_Init_800EEB00(void) { }
__attribute__((weak)) void ftKb_Init_800EEB1C(void) { }
__attribute__((weak)) void ftKb_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftKb_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftKb_Init_DatFilename(void) { }
__attribute__((weak)) void ftKb_Init_DataName(void) { }
__attribute__((weak)) void ftKb_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftKb_Init_GetMotionFileString(void) { }
__attribute__((weak)) void ftKb_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftKb_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftKb_Init_OnDeath(void) { }
__attribute__((weak)) void ftKb_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftKb_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftKb_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftKb_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftKb_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftKb_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftKb_Init_OnLoad(void) { }
__attribute__((weak)) void ftKb_Init_UnkCallbackPairs0_0(void) { }
__attribute__((weak)) void ftKb_Init_UnkCallbackPairs0_1(void) { }
__attribute__((weak)) void ftKb_Init_UnkDemoCallbacks0(void) { }
__attribute__((weak)) void ftKb_Init_UnkMotionStates0(void) { }
__attribute__((weak)) void ftKb_Init_UnkMotionStates3(void) { }
__attribute__((weak)) void ftKb_Init_UnkMotionStates4(void) { }
__attribute__((weak)) void ftKb_Init_UnkMotionStates5(void) { }
__attribute__((weak)) void ftKb_Init_UnkMotionStates6(void) { }
__attribute__((weak)) void ftKb_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftKb_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftKb_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftKb_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftKb_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftKb_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftKb_SpecialN_800EEC34(void) { }
__attribute__((weak)) void ftKb_SpecialN_800EEEC4(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F190C(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F1CD8(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F1D24(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F1F1C(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F1F68(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5820(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5874(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5898(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F58AC(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F58D8(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5954(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F597C(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F598C(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5A04(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5A38(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5A60(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5A70(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5A88(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5A98(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5AB0(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5AC0(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5AD8(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5AF0(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5B00(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5B10(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5B20(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5B3C(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5B4C(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5B5C(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5BA4(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5C34(void) { }
__attribute__((weak)) void ftKb_SpecialN_800F5D04(void) { }
__attribute__((weak)) void ftKb_SpecialN_Enter(void) { }
__attribute__((weak)) void ftKb_SpecialS_Enter(void) { }
__attribute__((weak)) void ftKb_UnkIntBoolFunc0(void) { }
__attribute__((weak)) void ftKb_UnkMtxFunc0(void) { }
__attribute__((weak)) void ftKp_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftKp_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftKp_Init_DatFilename(void) { }
__attribute__((weak)) void ftKp_Init_DataName(void) { }
__attribute__((weak)) void ftKp_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftKp_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftKp_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftKp_Init_OnDeath(void) { }
__attribute__((weak)) void ftKp_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftKp_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftKp_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftKp_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftKp_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftKp_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftKp_Init_OnLoad(void) { }
__attribute__((weak)) void ftKp_Init_UnkMotionStates3(void) { }
__attribute__((weak)) void ftKp_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftKp_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftKp_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftKp_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftKp_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftKp_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftKp_SpecialN_Enter(void) { }
__attribute__((weak)) void ftKp_SpecialS_80132DC0(void) { }
__attribute__((weak)) void ftKp_SpecialS_80132DD0(void) { }
__attribute__((weak)) void ftKp_SpecialS_80132DE0(void) { }
__attribute__((weak)) void ftKp_SpecialS_80132DF0(void) { }
__attribute__((weak)) void ftKp_SpecialS_80132E00(void) { }
__attribute__((weak)) void ftKp_SpecialS_80132E10(void) { }
__attribute__((weak)) void ftKp_SpecialS_80132E20(void) { }
__attribute__((weak)) void ftKp_SpecialS_Enter(void) { }
__attribute__((weak)) void ftLg_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftLg_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftLg_Init_DatFilename(void) { }
__attribute__((weak)) void ftLg_Init_DataName(void) { }
__attribute__((weak)) void ftLg_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftLg_Init_GetMotionFileString(void) { }
__attribute__((weak)) void ftLg_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftLg_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftLg_Init_OnDeath(void) { }
__attribute__((weak)) void ftLg_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftLg_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftLg_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftLg_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftLg_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftLg_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftLg_Init_OnLoad(void) { }
__attribute__((weak)) void ftLg_Init_UnkDemoCallbacks0(void) { }
__attribute__((weak)) void ftLg_Init_UnkMotionStates0(void) { }
__attribute__((weak)) void ftLg_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftLg_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftLg_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftLg_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftLg_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftLg_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftLg_SpecialN_Enter(void) { }
__attribute__((weak)) void ftLg_SpecialS_Enter(void) { }
__attribute__((weak)) void ftLk_AttackAir_800EB3BC(void) { }
__attribute__((weak)) void ftLk_AttackAir_Enter(void) { }
__attribute__((weak)) void ftLk_Init_803C82EC(void) { }
__attribute__((weak)) void ftLk_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftLk_Init_BoomerangExists(void) { }
__attribute__((weak)) void ftLk_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftLk_Init_DatFilename(void) { }
__attribute__((weak)) void ftLk_Init_DataName(void) { }
__attribute__((weak)) void ftLk_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftLk_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftLk_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftLk_Init_OnDeath(void) { }
__attribute__((weak)) void ftLk_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftLk_Init_OnItemDropExt(void) { }
__attribute__((weak)) void ftLk_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftLk_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftLk_Init_OnItemPickupExt(void) { }
__attribute__((weak)) void ftLk_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftLk_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftLk_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftLk_Init_OnLoad(void) { }
__attribute__((weak)) void ftLk_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftLk_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftLk_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftLk_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftLk_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftLk_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftLk_SpecialN_Enter(void) { }
__attribute__((weak)) void ftLk_SpecialS_Enter(void) { }
__attribute__((weak)) void ftMh_CaptureDamageMasterHand_Anim(void) { }
__attribute__((weak)) void ftMh_CaptureDamageMasterHand_Coll(void) { }
__attribute__((weak)) void ftMh_CaptureDamageMasterHand_IASA(void) { }
__attribute__((weak)) void ftMh_CaptureDamageMasterHand_Phys(void) { }
__attribute__((weak)) void ftMh_CaptureMasterHand_Anim(void) { }
__attribute__((weak)) void ftMh_CaptureMasterHand_Coll(void) { }
__attribute__((weak)) void ftMh_CaptureMasterHand_IASA(void) { }
__attribute__((weak)) void ftMh_CaptureMasterHand_Phys(void) { }
__attribute__((weak)) void ftMh_CaptureWaitMasterHand_Anim(void) { }
__attribute__((weak)) void ftMh_CaptureWaitMasterHand_Coll(void) { }
__attribute__((weak)) void ftMh_CaptureWaitMasterHand_IASA(void) { }
__attribute__((weak)) void ftMh_CaptureWaitMasterHand_Phys(void) { }
__attribute__((weak)) void ftMh_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftMh_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftMh_Init_DatFilename(void) { }
__attribute__((weak)) void ftMh_Init_DataName(void) { }
__attribute__((weak)) void ftMh_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftMh_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftMh_Init_OnDeath(void) { }
__attribute__((weak)) void ftMh_Init_OnLoad(void) { }
__attribute__((weak)) void ftMh_MS_341_8014FE10(void) { }
__attribute__((weak)) void ftMh_MS_341_8014FE58(void) { }
__attribute__((weak)) void ftMh_MS_389_80151018(void) { }
__attribute__((weak)) void ftMh_ThrownMasterHand_Anim(void) { }
__attribute__((weak)) void ftMh_ThrownMasterHand_Coll(void) { }
__attribute__((weak)) void ftMh_ThrownMasterHand_IASA(void) { }
__attribute__((weak)) void ftMh_ThrownMasterHand_Phys(void) { }
__attribute__((weak)) void ftMs_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftMs_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftMs_Init_DatFilename(void) { }
__attribute__((weak)) void ftMs_Init_DataName(void) { }
__attribute__((weak)) void ftMs_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftMs_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftMs_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftMs_Init_OnDeath(void) { }
__attribute__((weak)) void ftMs_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftMs_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftMs_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftMs_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftMs_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftMs_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftMs_Init_OnLoad(void) { }
__attribute__((weak)) void ftMs_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftMs_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftMs_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftMs_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftMs_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftMs_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftMs_SpecialN_Enter(void) { }
__attribute__((weak)) void ftMs_SpecialS_Enter(void) { }
__attribute__((weak)) void ftMt_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftMt_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftMt_Init_DatFilename(void) { }
__attribute__((weak)) void ftMt_Init_DataName(void) { }
__attribute__((weak)) void ftMt_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftMt_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftMt_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftMt_Init_OnDeath(void) { }
__attribute__((weak)) void ftMt_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftMt_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftMt_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftMt_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftMt_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftMt_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftMt_Init_OnLoad(void) { }
__attribute__((weak)) void ftMt_Init_UnkMotionStates4(void) { }
__attribute__((weak)) void ftMt_SpecialAirHiStart_Enter(void) { }
__attribute__((weak)) void ftMt_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftMt_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftMt_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftMt_SpecialHiStart_Enter(void) { }
__attribute__((weak)) void ftMt_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftMt_SpecialN_Enter(void) { }
__attribute__((weak)) void ftMt_SpecialN_Shoot(void) { }
__attribute__((weak)) void ftMt_SpecialS_Enter(void) { }
__attribute__((weak)) void ftNn_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftNn_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftNn_Init_DatFilename(void) { }
__attribute__((weak)) void ftNn_Init_DataName(void) { }
__attribute__((weak)) void ftNn_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftNn_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftNn_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftNn_Init_OnDeath(void) { }
__attribute__((weak)) void ftNn_Init_OnLoad(void) { }
__attribute__((weak)) void ftNs_AttackHi4_Enter(void) { }
__attribute__((weak)) void ftNs_AttackLw4_Enter(void) { }
__attribute__((weak)) void ftNs_AttackS4_Enter(void) { }
__attribute__((weak)) void ftNs_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftNs_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftNs_Init_DatFilename(void) { }
__attribute__((weak)) void ftNs_Init_DataName(void) { }
__attribute__((weak)) void ftNs_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftNs_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftNs_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftNs_Init_OnAbsorb(void) { }
__attribute__((weak)) void ftNs_Init_OnDeath(void) { }
__attribute__((weak)) void ftNs_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftNs_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftNs_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftNs_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftNs_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftNs_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftNs_Init_OnLoad(void) { }
__attribute__((weak)) void ftNs_SpecialAirHiStart_Enter(void) { }
__attribute__((weak)) void ftNs_SpecialAirLwStart_Enter(void) { }
__attribute__((weak)) void ftNs_SpecialAirNStart_Enter(void) { }
__attribute__((weak)) void ftNs_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftNs_SpecialHiStart_Enter(void) { }
__attribute__((weak)) void ftNs_SpecialLwStart_Enter(void) { }
__attribute__((weak)) void ftNs_SpecialNStart_Enter(void) { }
__attribute__((weak)) void ftNs_SpecialS_Enter(void) { }
__attribute__((weak)) void ftPc_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftPc_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftPc_Init_DatFilename(void) { }
__attribute__((weak)) void ftPc_Init_DataName(void) { }
__attribute__((weak)) void ftPc_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftPc_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftPc_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftPc_Init_OnDeath(void) { }
__attribute__((weak)) void ftPc_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftPc_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftPc_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftPc_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftPc_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftPc_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftPc_Init_OnLoad(void) { }
__attribute__((weak)) void ftPe_8011BA54(void) { }
__attribute__((weak)) void ftPe_8011BAD8(void) { }
__attribute__((weak)) void ftPe_8011D598(void) { }
__attribute__((weak)) void ftPe_AttackS4_Enter(void) { }
__attribute__((weak)) void ftPe_Init_8011B93C(void) { }
__attribute__((weak)) void ftPe_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftPe_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftPe_Init_DatFilename(void) { }
__attribute__((weak)) void ftPe_Init_DataName(void) { }
__attribute__((weak)) void ftPe_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftPe_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftPe_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftPe_Init_OnDeath(void) { }
__attribute__((weak)) void ftPe_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftPe_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftPe_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftPe_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftPe_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftPe_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftPe_Init_OnLoad(void) { }
__attribute__((weak)) void ftPe_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftPe_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftPe_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftPe_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftPe_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftPe_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftPe_SpecialN_Enter(void) { }
__attribute__((weak)) void ftPe_SpecialS_Enter(void) { }
__attribute__((weak)) void ftPk_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftPk_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftPk_Init_DatFilename(void) { }
__attribute__((weak)) void ftPk_Init_DataName(void) { }
__attribute__((weak)) void ftPk_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftPk_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftPk_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftPk_Init_OnDeath(void) { }
__attribute__((weak)) void ftPk_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftPk_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftPk_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftPk_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftPk_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftPk_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftPk_Init_OnLoad(void) { }
__attribute__((weak)) void ftPk_Init_UnkMotionStates1(void) { }
__attribute__((weak)) void ftPk_Init_UnkMotionStates2(void) { }
__attribute__((weak)) void ftPk_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftPk_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftPk_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftPk_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftPk_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftPk_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftPk_SpecialN_Enter(void) { }
__attribute__((weak)) void ftPk_SpecialS_Enter(void) { }
__attribute__((weak)) void ftPp_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftPp_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftPp_Init_DatFilename(void) { }
__attribute__((weak)) void ftPp_Init_DataName(void) { }
__attribute__((weak)) void ftPp_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftPp_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftPp_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftPp_Init_OnDeath(void) { }
__attribute__((weak)) void ftPp_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftPp_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftPp_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftPp_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftPp_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftPp_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftPp_Init_OnLoad(void) { }
__attribute__((weak)) void ftPp_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftPp_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftPp_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftPp_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftPp_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftPp_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftPp_SpecialN_Enter(void) { }
__attribute__((weak)) void ftPp_SpecialS_Enter(void) { }
__attribute__((weak)) void ftPr_Init_8013C2F8(void) { }
__attribute__((weak)) void ftPr_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftPr_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftPr_Init_DatFilename(void) { }
__attribute__((weak)) void ftPr_Init_DataName(void) { }
__attribute__((weak)) void ftPr_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftPr_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftPr_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftPr_Init_OnDeath(void) { }
__attribute__((weak)) void ftPr_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftPr_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftPr_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftPr_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftPr_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftPr_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftPr_Init_OnLoad(void) { }
__attribute__((weak)) void ftPr_Init_OnUserDataRemove(void) { }
__attribute__((weak)) void ftPr_Init_UnkIntBoolFunc0(void) { }
__attribute__((weak)) void ftPr_Init_UnkMotionStates6(void) { }
__attribute__((weak)) void ftPr_Init_UnkMtxFunc0(void) { }
__attribute__((weak)) void ftPr_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftPr_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftPr_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftPr_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftPr_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftPr_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftPr_SpecialN_Enter(void) { }
__attribute__((weak)) void ftPr_SpecialS_Enter(void) { }
__attribute__((weak)) void ftSb_Init_8014FBA4(void) { }
__attribute__((weak)) void ftSb_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftSb_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftSb_Init_DatFilename(void) { }
__attribute__((weak)) void ftSb_Init_DataName(void) { }
__attribute__((weak)) void ftSb_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftSb_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftSb_Init_OnDeath(void) { }
__attribute__((weak)) void ftSb_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftSb_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftSb_Init_OnLoad(void) { }
__attribute__((weak)) void ftSk_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftSk_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftSk_Init_DatFilename(void) { }
__attribute__((weak)) void ftSk_Init_DataName(void) { }
__attribute__((weak)) void ftSk_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftSk_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftSk_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftSk_Init_OnDeath(void) { }
__attribute__((weak)) void ftSk_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftSk_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftSk_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftSk_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftSk_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftSk_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftSk_Init_OnLoad(void) { }
__attribute__((weak)) void ftSk_Init_UnkMotionStates4(void) { }
__attribute__((weak)) void ftSk_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftSk_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftSk_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftSk_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftSk_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftSk_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftSk_SpecialN_Enter(void) { }
__attribute__((weak)) void ftSk_SpecialS_Enter(void) { }
__attribute__((weak)) void ftSs_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftSs_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftSs_Init_CreateThrowGrappleBeam(void) { }
__attribute__((weak)) void ftSs_Init_DatFilename(void) { }
__attribute__((weak)) void ftSs_Init_DataName(void) { }
__attribute__((weak)) void ftSs_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftSs_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftSs_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftSs_Init_OnDeath(void) { }
__attribute__((weak)) void ftSs_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftSs_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftSs_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftSs_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftSs_Init_OnLoad(void) { }
__attribute__((weak)) void ftSs_Init_UnkMotionStates4(void) { }
__attribute__((weak)) void ftSs_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftSs_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftSs_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftSs_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftSs_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftSs_SpecialLw_8012AEBC(void) { }
__attribute__((weak)) void ftSs_SpecialLw_8012AF38(void) { }
__attribute__((weak)) void ftSs_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftSs_SpecialN_Enter(void) { }
__attribute__((weak)) void ftSs_SpecialS_Enter(void) { }
__attribute__((weak)) void ftYs_Init_8012B8A4(void) { }
__attribute__((weak)) void ftYs_Init_8012BAC0(void) { }
__attribute__((weak)) void ftYs_Init_8012BDA0(void) { }
__attribute__((weak)) void ftYs_Init_8012BE3C(void) { }
__attribute__((weak)) void ftYs_Init_8012BECC(void) { }
__attribute__((weak)) void ftYs_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftYs_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftYs_Init_DatFilename(void) { }
__attribute__((weak)) void ftYs_Init_DataName(void) { }
__attribute__((weak)) void ftYs_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftYs_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftYs_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftYs_Init_OnDeath(void) { }
__attribute__((weak)) void ftYs_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftYs_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftYs_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftYs_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftYs_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftYs_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftYs_Init_OnLoad(void) { }
__attribute__((weak)) void ftYs_Shield_8012C1D4(void) { }
__attribute__((weak)) void ftYs_Shield_8012C49C(void) { }
__attribute__((weak)) void ftYs_Shield_8012C600(void) { }
__attribute__((weak)) void ftYs_Shield_8012C850(void) { }
__attribute__((weak)) void ftYs_Shield_8012C914(void) { }
__attribute__((weak)) void ftYs_Shield_8012CC1C(void) { }
__attribute__((weak)) void ftYs_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftYs_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftYs_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftYs_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftYs_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftYs_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftYs_SpecialN_8012CD40(void) { }
__attribute__((weak)) void ftYs_SpecialN_8012CD88(void) { }
__attribute__((weak)) void ftYs_SpecialN_8012CDB4(void) { }
__attribute__((weak)) void ftYs_SpecialN_8012CDD4(void) { }
__attribute__((weak)) void ftYs_SpecialN_Enter(void) { }
__attribute__((weak)) int ftYs_SpecialN_GetDatAttr18(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetDatAttr1C(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetDatAttr20(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetDatAttr24(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetExtAttr28(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetExtAttr2C(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetExtAttr34(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetExtAttr38(void) { return 0; }
__attribute__((weak)) int ftYs_SpecialN_GetFacingDir(void) { return 0; }
__attribute__((weak)) void ftYs_SpecialN_SetupItemVel(void) { }
__attribute__((weak)) void ftYs_SpecialS_Enter(void) { }
__attribute__((weak)) void ftZd_Init_801395C8(void) { }
__attribute__((weak)) void ftZd_Init_AnimDatFilename(void) { }
__attribute__((weak)) void ftZd_Init_CostumeStrings(void) { }
__attribute__((weak)) void ftZd_Init_DatFilename(void) { }
__attribute__((weak)) void ftZd_Init_DataName(void) { }
__attribute__((weak)) void ftZd_Init_DemoMotionFilenames(void) { }
__attribute__((weak)) void ftZd_Init_LoadSpecialAttrs(void) { }
__attribute__((weak)) void ftZd_Init_MotionStateTable(void) { }
__attribute__((weak)) void ftZd_Init_OnDeath(void) { }
__attribute__((weak)) void ftZd_Init_OnItemDrop(void) { }
__attribute__((weak)) void ftZd_Init_OnItemInvisible(void) { }
__attribute__((weak)) void ftZd_Init_OnItemPickup(void) { }
__attribute__((weak)) void ftZd_Init_OnItemVisible(void) { }
__attribute__((weak)) void ftZd_Init_OnKnockbackEnter(void) { }
__attribute__((weak)) void ftZd_Init_OnKnockbackExit(void) { }
__attribute__((weak)) void ftZd_Init_OnLoad(void) { }
__attribute__((weak)) void ftZd_SpecialAirHi_Enter(void) { }
__attribute__((weak)) void ftZd_SpecialAirLw_Enter(void) { }
__attribute__((weak)) void ftZd_SpecialAirN_Enter(void) { }
__attribute__((weak)) void ftZd_SpecialAirS_Enter(void) { }
__attribute__((weak)) void ftZd_SpecialHi_Enter(void) { }
__attribute__((weak)) void ftZd_SpecialLw_Enter(void) { }
__attribute__((weak)) void ftZd_SpecialN_Enter(void) { }
__attribute__((weak)) void ftZd_SpecialS_Enter(void) { }
__attribute__((weak)) void gm_80167320(void) { }
__attribute__((weak)) void gm_8016B248(void) { }
__attribute__((weak)) void gm_8016B41C(void) { }
__attribute__((weak)) void gm_8016B558(void) { }
__attribute__((weak)) void gm_8016B6E8(void) { }
__attribute__((weak)) void gm_8016C75C(void) { }
__attribute__((weak)) void gm_8016F2F8(void) { }
__attribute__((weak)) void gm_801720B4(void) { }
__attribute__((weak)) void gm_801720F8(void) { }
__attribute__((weak)) void gm_80172140(void) { }
__attribute__((weak)) void gm_801A4BB8(void) { }
__attribute__((weak)) int gm_GetCurrentGameMode(void) { return 0; }
__attribute__((weak)) void ifMagnify_802FB6E8(void) { }
__attribute__((weak)) void ifMagnify_802FC998(void) { }
__attribute__((weak)) void itDrMarioPill_802C09C4(void) { }
__attribute__((weak)) void* itDrMarioPill_Spawn(void) { return NULL; }
__attribute__((weak)) int itGetAttackId(void) { return 0; }
__attribute__((weak)) int itGetDamageMultiplier(void) { return 0; }
__attribute__((weak)) int itGetGrabRangeX(void) { return 0; }
__attribute__((weak)) int itGetGrabRangeY(void) { return 0; }
__attribute__((weak)) int itGetHoldKind(void) { return 0; }
__attribute__((weak)) int itGetMotionId(void) { return 0; }
__attribute__((weak)) int itGetOwner(void) { return 0; }
__attribute__((weak)) void itIsHeavy(void) { }
__attribute__((weak)) void it_8026B1D4(void) { }
__attribute__((weak)) void it_8026B2D8(void) { }
__attribute__((weak)) void it_8026B30C(void) { }
__attribute__((weak)) void it_8026B344(void) { }
__attribute__((weak)) void it_8026B3F8(void) { }
__attribute__((weak)) void it_8026B47C(void) { }
__attribute__((weak)) void it_8026B4F0(void) { }
__attribute__((weak)) void it_8026B54C(void) { }
__attribute__((weak)) void it_8026B560(void) { }
__attribute__((weak)) void it_8026B574(void) { }
__attribute__((weak)) void it_8026B588(void) { }
__attribute__((weak)) void it_8026B594(void) { }
__attribute__((weak)) void it_8026B6C8(void) { }
__attribute__((weak)) void it_8026B774(void) { }
__attribute__((weak)) void it_8026B7BC(void) { }
__attribute__((weak)) void it_8026B7CC(void) { }
__attribute__((weak)) void it_8026B7D8(void) { }
__attribute__((weak)) void it_8026B7E0(void) { }
__attribute__((weak)) void it_8026B7E8(void) { }
__attribute__((weak)) void it_8026B7F8(void) { }
__attribute__((weak)) void it_8026B9A8(void) { }
__attribute__((weak)) void it_8026BAE8(void) { }
__attribute__((weak)) void it_8026BC68(void) { }
__attribute__((weak)) void it_8026BCF4(void) { }
__attribute__((weak)) void it_8026BD0C(void) { }
__attribute__((weak)) void it_8026C16C(void) { }
__attribute__((weak)) void it_8026C1D4(void) { }
__attribute__((weak)) void it_8026C334(void) { }
__attribute__((weak)) void it_8026C3FC(void) { }
__attribute__((weak)) void it_8026C42C(void) { }
__attribute__((weak)) void it_8026FAC4(void) { }
__attribute__((weak)) void it_8026FC00(void) { }
__attribute__((weak)) void it_80272818(void) { }
__attribute__((weak)) void it_80272C90(void) { }
__attribute__((weak)) void it_8027B070(void) { }
__attribute__((weak)) void it_8027B4A4(void) { }
__attribute__((weak)) void it_80284FC4(void) { }
__attribute__((weak)) void it_80285024(void) { }
__attribute__((weak)) void it_802852B8(void) { }
__attribute__((weak)) void it_80285300(void) { }
__attribute__((weak)) void it_80285314(void) { }
__attribute__((weak)) void it_8028B08C(void) { }
__attribute__((weak)) void it_8028B618(void) { }
__attribute__((weak)) void it_8028B648(void) { }
__attribute__((weak)) void it_8028B6B0(void) { }
__attribute__((weak)) void it_8028B718(void) { }
__attribute__((weak)) void it_8028B780(void) { }
__attribute__((weak)) void it_8028B7E8(void) { }
__attribute__((weak)) void it_8028B850(void) { }
__attribute__((weak)) void it_8028E774(void) { }
__attribute__((weak)) void it_8028E79C(void) { }
__attribute__((weak)) void it_8028E938(void) { }
__attribute__((weak)) void it_80291CCC(void) { }
__attribute__((weak)) void it_80291CF4(void) { }
__attribute__((weak)) void it_80291DAC(void) { }
__attribute__((weak)) void it_80291F14(void) { }
__attribute__((weak)) void it_80291FA8(void) { }
__attribute__((weak)) void it_80292394(void) { }
__attribute__((weak)) void it_802923BC(void) { }
__attribute__((weak)) void it_802927E8(void) { }
__attribute__((weak)) void it_8029282C(void) { }
__attribute__((weak)) void it_80292998(void) { }
__attribute__((weak)) void it_802929C8(void) { }
__attribute__((weak)) void it_802929F8(void) { }
__attribute__((weak)) void it_80292A28(void) { }
__attribute__((weak)) void it_80292E64(void) { }
__attribute__((weak)) void it_80292EAC(void) { }
__attribute__((weak)) void it_80292EF8(void) { }
__attribute__((weak)) void it_80292F14(void) { }
__attribute__((weak)) void it_80293660(void) { }
__attribute__((weak)) void it_80293DCC(void) { }
__attribute__((weak)) void it_80293E34(void) { }
__attribute__((weak)) void it_80294364(void) { }
__attribute__((weak)) void it_80294430(void) { }
__attribute__((weak)) void it_802944AC(void) { }
__attribute__((weak)) void it_802946B0(void) { }
__attribute__((weak)) void it_802947CC(void) { }
__attribute__((weak)) void it_80294E78(void) { }
__attribute__((weak)) void it_80294EB0(void) { }
__attribute__((weak)) void it_802950D4(void) { }
__attribute__((weak)) void it_80295748(void) { }
__attribute__((weak)) void it_80295770(void) { }
__attribute__((weak)) void it_80295F38(void) { }
__attribute__((weak)) void it_802960B8(void) { }
__attribute__((weak)) void it_802960CC(void) { }
__attribute__((weak)) void it_8029A748(void) { }
__attribute__((weak)) void it_8029A89C(void) { }
__attribute__((weak)) void it_8029A8F4(void) { }
__attribute__((weak)) void it_8029B6F8(void) { }
__attribute__((weak)) void it_802A2B10(void) { }
__attribute__((weak)) void it_802A2BA4(void) { }
__attribute__((weak)) void it_802A77DC(void) { }
__attribute__((weak)) void it_802A7840(void) { }
__attribute__((weak)) void it_802A78B8(void) { }
__attribute__((weak)) void it_802A7AAC(void) { }
__attribute__((weak)) void it_802A7AF0(void) { }
__attribute__((weak)) void it_802A7B34(void) { }
__attribute__((weak)) void it_802AD590(void) { }
__attribute__((weak)) void it_802AE994(void) { }
__attribute__((weak)) void it_802B2560(void) { }
__attribute__((weak)) void it_802B2674(void) { }
__attribute__((weak)) void it_802B26C0(void) { }
__attribute__((weak)) void it_802B26E0(void) { }
__attribute__((weak)) void it_802B7B84(void) { }
__attribute__((weak)) void it_802B7C18(void) { }
__attribute__((weak)) void it_802BAA58(void) { }
__attribute__((weak)) void it_802BAA94(void) { }
__attribute__((weak)) void it_802BAAE4(void) { }
__attribute__((weak)) void it_802BAC3C(void) { }
__attribute__((weak)) void it_802BAC80(void) { }
__attribute__((weak)) void it_802BACC4(void) { }
__attribute__((weak)) void it_802BDA40(void) { }
__attribute__((weak)) void it_802BDB94(void) { }
__attribute__((weak)) void it_802BDD40(void) { }
__attribute__((weak)) void it_802BDDB4(void) { }
__attribute__((weak)) void it_802DB9F4(void) { }
__attribute__((weak)) void it_802DBA68(void) { }
__attribute__((weak)) void it_802E5EF4(void) { }
__attribute__((weak)) void it_802E5F8C(void) { }
__attribute__((weak)) void it_802EAAEC(void) { }
__attribute__((weak)) void it_802EADD8(void) { }
__attribute__((weak)) void it_802EAE80(void) { }
__attribute__((weak)) void it_802EAF28(void) { }
__attribute__((weak)) void it_804D6D28(void) { }
__attribute__((weak)) void lbRefSetUnuse(void) { }
__attribute__((weak)) int mpCheckAllRemap(void) { return 0; }
__attribute__((weak)) int mpCheckLeftWall(void) { return 0; }
__attribute__((weak)) int mpCheckRightWall(void) { return 0; }
__attribute__((weak)) void mpClearFloorSkip(void) { }
__attribute__((weak)) void mpCollSetFacingDir(void) { }
__attribute__((weak)) void mpColl_80041EE4(void) { }
__attribute__((weak)) void mpColl_80043670(void) { }
__attribute__((weak)) void mpColl_80043680(void) { }
__attribute__((weak)) void mpColl_80044164(void) { }
__attribute__((weak)) void mpColl_800443C4(void) { }
__attribute__((weak)) void mpColl_800471F8(void) { }
__attribute__((weak)) void mpColl_8004730C(void) { }
__attribute__((weak)) void mpColl_800473CC(void) { }
__attribute__((weak)) void mpColl_800474E0(void) { }
__attribute__((weak)) void mpColl_800475F4(void) { }
__attribute__((weak)) void mpColl_800476B4(void) { }
__attribute__((weak)) void mpColl_800477E0(void) { }
__attribute__((weak)) void mpColl_800478F4(void) { }
__attribute__((weak)) void mpColl_80047A08(void) { }
__attribute__((weak)) void mpColl_80047AC8(void) { }
__attribute__((weak)) void mpColl_80047BF4(void) { }
__attribute__((weak)) void mpColl_80047D20(void) { }
__attribute__((weak)) void mpColl_80047E14(void) { }
__attribute__((weak)) void mpColl_80047F40(void) { }
__attribute__((weak)) void mpColl_8004806C(void) { }
__attribute__((weak)) void mpColl_80048160(void) { }
__attribute__((weak)) void mpColl_80048274(void) { }
__attribute__((weak)) void mpColl_80048388(void) { }
__attribute__((weak)) void mpColl_80048464(void) { }
__attribute__((weak)) void mpColl_80048578(void) { }
__attribute__((weak)) void mpColl_80048654(void) { }
__attribute__((weak)) void mpColl_80048768(void) { }
__attribute__((weak)) void mpColl_8004B108(void) { }
__attribute__((weak)) void mpColl_8004B21C(void) { }
__attribute__((weak)) void mpColl_8004B2DC(void) { }
__attribute__((weak)) void mpColl_8004B3F0(void) { }
__attribute__((weak)) void mpColl_8004B4B0(void) { }
__attribute__((weak)) void mpColl_8004B5C4(void) { }
__attribute__((weak)) void mpColl_8004CA6C(void) { }
__attribute__((weak)) void mpColl_IsOnPlatform(void) { }
__attribute__((weak)) void mpColl_SetECBSource_JObj(void) { }
__attribute__((weak)) void mpColl_SetLedgeSnap(void) { }
__attribute__((weak)) void* mpCopyCollData(void) { return NULL; }
__attribute__((weak)) int mpFloorGetLeft(void) { return 0; }
__attribute__((weak)) int mpFloorGetRight(void) { return 0; }
__attribute__((weak)) int mpGetSpeed(void) { return 0; }
__attribute__((weak)) void mpIsland_8005AB54(void) { }
__attribute__((weak)) void mpIsland_8005AC8C(void) { }
__attribute__((weak)) void mpIsland_80458E88(void) { }
__attribute__((weak)) void mpLib_8004DD90_Floor(void) { }
__attribute__((weak)) void mpLib_8005199C_Floor(void) { }
__attribute__((weak)) void mpLib_80053DA4_Floor(void) { }
__attribute__((weak)) void mpLib_80053ECC_Floor(void) { }
__attribute__((weak)) void mpLib_80054ED8(void) { }
__attribute__((weak)) void mpLib_80056A1C(void) { }
__attribute__((weak)) void mpLib_80056A54(void) { }
__attribute__((weak)) void mpLib_80056A8C(void) { }
__attribute__((weak)) void mpLib_80056AC4(void) { }
__attribute__((weak)) void mpLib_80056AFC(void) { }
__attribute__((weak)) void mpLib_80056B34(void) { }
__attribute__((weak)) void mpLib_8005811C(void) { }
__attribute__((weak)) int mpLineGetFlags(void) { return 0; }
__attribute__((weak)) int mpLineGetNext(void) { return 0; }
__attribute__((weak)) int mpLineGetNormal(void) { return 0; }
__attribute__((weak)) int mpLineGetPrev(void) { return 0; }
__attribute__((weak)) int mpLineGetV0Pos(void) { return 0; }
__attribute__((weak)) int mpLineGetV1Pos(void) { return 0; }
__attribute__((weak)) void mpUpdateFloorSkip(void) { }
__attribute__((weak)) void un_80322258(void) { }
__attribute__((weak)) void un_803222EC(void) { }
__attribute__((weak)) void un_80322314(void) { }
__attribute__((weak)) void un_8032233C(void) { }
__attribute__((weak)) void un_803224DC(void) { }
__attribute__((weak)) void un_80322598(void) { }
